os: linux
dist: bionic
stages:
  - name: Test
  - name: Deploy
jobs:
  - include:
    - stage: Unit Test
      name: "Unit Test 3.7"
      install:
        - pip install codecov
        - pip install -r requirements.txt
      script: coverage run -m unittest discover tests -b
      after_sucess: codecov
      python: "3.7"
    - stage: Unit Test
      name: "Unit Test 3.8"
      install:
        - pip install codecov
        - pip install -r requirements.txt
      script: coverage run -m unittest discover tests -b
      after_sucess: codecov
      python: "3.8"
    - stage: Unit Test
      name: "Unit Test 3.9"
      install:
        - pip install codecov
        - pip install -r requirements.txt
      script: coverage run -m unittest discover tests -b
      after_sucess: codecov
      python: "3.9-dev"
    - stage: Unit Test
      name: "Unit Test Nightly"
      install:
        - pip install codecov
        - pip install -r requirements.txt
      script: coverage run -m unittest discover tests -b
      after_sucess: codecov
      python: "nightly"
    - stage: Pip Test
      name: "Pip Test 3.5"
      install:
        - pip install -r requirements.txt
        - pip install .
      script: python -m unittest test_pip.py
      python: "3.5"
    - stage: Pip Test
      name: "Pip Test 3.6"
      install:
        - pip install -r requirements.txt
        - pip install .
      script: python -m unittest test_pip.py
      python: "3.6"
      name: "Pip Test 3.7"
      install:
        - pip install -r requirements.txt
        - pip install .
      script: python -m unittest test_pip.py
      python: "3.7"
      name: "Pip Test 3.8"
      install:
        - pip install -r requirements.txt
        - pip install .
      script: python -m unittest test_pip.py
      python: "3.8"
      name: "Pip Test 3.9"
      install:
        - pip install -r requirements.txt
        - pip install .
      script: python -m unittest test_pip.py
      python: "3.9-dev"
      name: "Pip Test Nightly"
      install:
        - pip install -r requirements.txt
        - pip install .
      script: python -m unittest test_pip.py
      python: "nightly"
