os: linux
dist: xenial 
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - nightly
matrix:
  allow_failures:
    - python: 2.7
install:
  - pip install codecov
  - pip install -r requirements.txt
script: coverage run -m unittest discover tests -b
after_success: codecov
