sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
install:
  - pip install codecov
  - pip install pyyaml
script: 
  - coverage run -m unittest discover tests -b
after_success:
  - codecov
