[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'phoebusgen'
author = [
    {name = 'Tynan Ford', email = 'tford@lbl.gov'}
]
description = 'Control screen generator for Phoebus'
readme = {file = 'README.md', content-type = 'text/markdown'}
requires-python = '>=3.5'
classifiers=[
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: GNU General Public License v2 (GPLv2)',
    'Operating System :: OS Independent',
    'Development Status :: 5 - Production/Stable',
    'Topic :: Software Development :: Code Generators'
]

[project.urls]
url = 'https://github.com/als-epics/phoebusgen'
