name: Build Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx 
        pip install sphinx_autodoc_typehints 
    - name: Build Docs
      run: ./docbuild/build-docs.sh
    - name: Archive docs
      uses: actions/upload-artifact@v3
      with:
        name: save-docs
        path: docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
