name: Build Docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: ".docbuild/"
        pre-build-command: "sphinx-apidoc -o ./source ../phoebusgen"
        build-command: "make html"
    - name: move-docs
      - run: cp -r _build/html/ ../docs
