name: Python unittest
permissions:
  contents: read
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        include:
          - python-version: "3.5"
            container: "python:3.5"
          - python-version: "3.6"
            container: "python:3.6"
          - python-version: "3.7"
            container: "python:3.7"
          - python-version: "3.8"
          - python-version: "3.9"
          - python-version: "3.10"
          - python-version: "3.11"
          - python-version: "3.12"
          - python-version: "3.13"
          - python-version: "3.14.0-rc.3"
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        if: ${{ !matrix.container }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r requirements.txt
      - name: Run tests with unittest and codecov
        run: coverage run -m unittest discover tests -b
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          verbose: false
